# Generated by Django 5.0.7 on 2024-08-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract3a_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_fee', models.IntegerField()),
                ('c_duration', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
