# Generated by Django 5.0.7 on 2024-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('month', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
