# Generated by Django 5.0.7 on 2024-08-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_fee', models.IntegerField()),
                ('c_duration', models.CharField(max_length=30)),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shrads_app.student')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
