# Generated by Django 5.0.7 on 2024-07-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
